/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Thor.glb 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/Thor.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="SK_1039_1039001">
          <primitive object={nodes.root} />
          <group name="SK_1039_1039001001">
            <skinnedMesh name="SK_1039_1039001_1" geometry={nodes.SK_1039_1039001_1.geometry} material={materials['MI_1039001_Eyes_01.001']} skeleton={nodes.SK_1039_1039001_1.skeleton} />
            <skinnedMesh name="SK_1039_1039001_2" geometry={nodes.SK_1039_1039001_2.geometry} material={materials['MI_1039001_Tooth.001']} skeleton={nodes.SK_1039_1039001_2.skeleton} />
            <skinnedMesh name="SK_1039_1039001_3" geometry={nodes.SK_1039_1039001_3.geometry} material={materials['MI_1039001_Hammer_Weapon_01.001']} skeleton={nodes.SK_1039_1039001_3.skeleton} />
            <skinnedMesh name="SK_1039_1039001_4" geometry={nodes.SK_1039_1039001_4.geometry} material={materials['MI_1039001_Head.001']} skeleton={nodes.SK_1039_1039001_4.skeleton} />
            <skinnedMesh name="SK_1039_1039001_5" geometry={nodes.SK_1039_1039001_5.geometry} material={materials['MI_1039001_Hair_01.001']} skeleton={nodes.SK_1039_1039001_5.skeleton} />
            <skinnedMesh name="SK_1039_1039001_6" geometry={nodes.SK_1039_1039001_6.geometry} material={materials['MI_1039001_Hammer_Weapon_01.001']} skeleton={nodes.SK_1039_1039001_6.skeleton} />
            <skinnedMesh name="SK_1039_1039001_7" geometry={nodes.SK_1039_1039001_7.geometry} material={materials['MI_1039001_Body.001']} skeleton={nodes.SK_1039_1039001_7.skeleton} />
            <skinnedMesh name="SK_1039_1039001_8" geometry={nodes.SK_1039_1039001_8.geometry} material={materials['MI_1039001_Equip_01.001']} skeleton={nodes.SK_1039_1039001_8.skeleton} />
            <skinnedMesh name="SK_1039_1039001_9" geometry={nodes.SK_1039_1039001_9.geometry} material={materials['MI_1039001_Equip_02.001']} skeleton={nodes.SK_1039_1039001_9.skeleton} />
            <skinnedMesh name="SK_1039_1039001_10" geometry={nodes.SK_1039_1039001_10.geometry} material={materials['MI_1039001_Hair_04.001']} skeleton={nodes.SK_1039_1039001_10.skeleton} />
            <skinnedMesh name="SK_1039_1039001_11" geometry={nodes.SK_1039_1039001_11.geometry} material={materials['MI_1039001_Hair_03.001']} skeleton={nodes.SK_1039_1039001_11.skeleton} />
            <skinnedMesh name="SK_1039_1039001_12" geometry={nodes.SK_1039_1039001_12.geometry} material={materials['MI_1039001_Eyes_02.001']} skeleton={nodes.SK_1039_1039001_12.skeleton} />
            <skinnedMesh name="SK_1039_1039001_13" geometry={nodes.SK_1039_1039001_13.geometry} material={materials['MI_1039001_Hair_02.001']} skeleton={nodes.SK_1039_1039001_13.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Thor.glb')
